/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rephial_angband_NativeWrapper */

#ifndef _Included_org_rephial_angband_NativeWrapper
#define _Included_org_rephial_angband_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rephial_angband_NativeWrapper
 * Method:    gameStart
 * Signature: (Ljava/lang/String;I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_rephial_angband_NativeWrapper_gameStart
  (JNIEnv *, jobject, jstring, jint, jobjectArray);

/*
 * Class:     org_rephial_angband_NativeWrapper
 * Method:    gameQueryInt
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_rephial_angband_NativeWrapper_gameQueryInt
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     org_rephial_angband_NativeWrapper
 * Method:    gameQueryString
 * Signature: (I[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_rephial_angband_NativeWrapper_gameQueryString
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
